// Autogenerated from Pigeon (v9.2.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, PigeonSensorPosition) {
  PigeonSensorPositionBack = 0,
  PigeonSensorPositionFront = 1,
  PigeonSensorPositionUnknown = 2,
};

/// Video recording quality, from [sd] to [uhd], with [highest] and [lowest] to
/// let the device choose the best/worst quality available.
/// [highest] is the default quality.
///
/// Qualities are defined like this:
/// [sd] < [hd] < [fhd] < [uhd]
typedef NS_ENUM(NSUInteger, VideoRecordingQuality) {
  VideoRecordingQualityLowest = 0,
  VideoRecordingQualitySd = 1,
  VideoRecordingQualityHd = 2,
  VideoRecordingQualityFhd = 3,
  VideoRecordingQualityUhd = 4,
  VideoRecordingQualityHighest = 5,
};

/// If the specified [VideoRecordingQuality] is not available on the device,
/// the [VideoRecordingQuality] will fallback to [higher] or [lower] quality.
/// [higher] is the default fallback strategy.
typedef NS_ENUM(NSUInteger, QualityFallbackStrategy) {
  QualityFallbackStrategyHigher = 0,
  QualityFallbackStrategyLower = 1,
};

typedef NS_ENUM(NSUInteger, CupertinoFileType) {
  CupertinoFileTypeQuickTimeMovie = 0,
  CupertinoFileTypeMpeg4 = 1,
  CupertinoFileTypeAppleM4V = 2,
  CupertinoFileTypeType3GPP = 3,
  CupertinoFileTypeType3GPP2 = 4,
};

typedef NS_ENUM(NSUInteger, CupertinoCodecType) {
  CupertinoCodecTypeH264 = 0,
  CupertinoCodecTypeHevc = 1,
  CupertinoCodecTypeHevcWithAlpha = 2,
  CupertinoCodecTypeJpeg = 3,
  CupertinoCodecTypeAppleProRes4444 = 4,
  CupertinoCodecTypeAppleProRes422 = 5,
  CupertinoCodecTypeAppleProRes422HQ = 6,
  CupertinoCodecTypeAppleProRes422LT = 7,
  CupertinoCodecTypeAppleProRes422Proxy = 8,
};

typedef NS_ENUM(NSUInteger, PigeonSensorType) {
  /// A built-in wide-angle camera.
  ///
  /// The wide angle sensor is the default sensor for iOS
  PigeonSensorTypeWideAngle = 0,
  /// A built-in camera with a shorter focal length than that of the wide-angle camera.
  PigeonSensorTypeUltraWideAngle = 1,
  /// A built-in camera device with a longer focal length than the wide-angle camera.
  PigeonSensorTypeTelephoto = 2,
  /// A device that consists of two cameras, one Infrared and one YUV.
  ///
  /// iOS only
  PigeonSensorTypeTrueDepth = 3,
  PigeonSensorTypeUnknown = 4,
};

typedef NS_ENUM(NSUInteger, CamerAwesomePermission) {
  CamerAwesomePermissionStorage = 0,
  CamerAwesomePermissionCamera = 1,
  CamerAwesomePermissionLocation = 2,
  CamerAwesomePermissionRecord_audio = 3,
};

typedef NS_ENUM(NSUInteger, AnalysisImageFormat) {
  AnalysisImageFormatYuv_420 = 0,
  AnalysisImageFormatBgra8888 = 1,
  AnalysisImageFormatJpeg = 2,
  AnalysisImageFormatNv21 = 3,
  AnalysisImageFormatUnknown = 4,
};

typedef NS_ENUM(NSUInteger, AnalysisRotation) {
  AnalysisRotationRotation0deg = 0,
  AnalysisRotationRotation90deg = 1,
  AnalysisRotationRotation180deg = 2,
  AnalysisRotationRotation270deg = 3,
};

/// Exposure mode mirroring `AVCaptureDevice.ExposureMode`.
/// [custom] lets you set ISO and shutter speed manually through
/// [CameraInterface.setManualExposure].
///
/// iOS only for now.
typedef NS_ENUM(NSUInteger, PigeonExposureMode) {
  PigeonExposureModeLocked = 0,
  PigeonExposureModeAuto = 1,
  PigeonExposureModeContinuousAuto = 2,
  PigeonExposureModeCustom = 3,
};

/// Focus mode mirroring `AVCaptureDevice.FocusMode`.
/// When [locked], use [CameraInterface.setLensPosition] to drive the lens
/// manually.
///
/// iOS only for now.
typedef NS_ENUM(NSUInteger, PigeonFocusMode) {
  PigeonFocusModeLocked = 0,
  PigeonFocusModeAuto = 1,
  PigeonFocusModeContinuousAuto = 2,
};

/// White balance mode mirroring `AVCaptureDevice.WhiteBalanceMode`.
/// When [locked], use [CameraInterface.setWhiteBalanceGains] or
/// [CameraInterface.setWhiteBalanceTemperatureTint] to set it manually.
///
/// iOS only for now.
typedef NS_ENUM(NSUInteger, PigeonWhiteBalanceMode) {
  PigeonWhiteBalanceModeLocked = 0,
  PigeonWhiteBalanceModeAuto = 1,
  PigeonWhiteBalanceModeContinuousAuto = 2,
};

/// Torch (continuous light) mode mirroring `AVCaptureDevice.TorchMode`.
/// This is independent from the photo flash configured with
/// [CameraInterface.setFlashMode].
///
/// iOS only for now.
typedef NS_ENUM(NSUInteger, PigeonTorchMode) {
  PigeonTorchModeOff = 0,
  PigeonTorchModeOn = 1,
  PigeonTorchModeAuto = 2,
};

/// Auto focus range restriction mirroring
/// `AVCaptureDevice.AutoFocusRangeRestriction`.
///
/// iOS only for now.
typedef NS_ENUM(NSUInteger, PigeonFocusRangeRestriction) {
  PigeonFocusRangeRestrictionNone = 0,
  PigeonFocusRangeRestrictionNear = 1,
  PigeonFocusRangeRestrictionFar = 2,
};

/// Color space mirroring `AVCaptureColorSpace`.
///
/// iOS only for now.
typedef NS_ENUM(NSUInteger, PigeonColorSpace) {
  PigeonColorSpaceSRGB = 0,
  PigeonColorSpaceP3D65 = 1,
  PigeonColorSpaceHlgBT2020 = 2,
  PigeonColorSpaceAppleLog = 3,
};

@class PreviewSize;
@class ExifPreferences;
@class PigeonSensor;
@class VideoOptions;
@class AndroidVideoOptions;
@class CupertinoVideoOptions;
@class PigeonSensorTypeDevice;
@class AndroidFocusSettings;
@class PlaneWrapper;
@class CropRectWrapper;
@class AnalysisImageWrapper;
@class PigeonExposureState;
@class PigeonWhiteBalanceGains;
@class PigeonCameraSettings;

@interface PreviewSize : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithWidth:(NSNumber *)width
    height:(NSNumber *)height;
@property(nonatomic, strong) NSNumber * width;
@property(nonatomic, strong) NSNumber * height;
@end

@interface ExifPreferences : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithSaveGPSLocation:(NSNumber *)saveGPSLocation;
@property(nonatomic, strong) NSNumber * saveGPSLocation;
@end

@interface PigeonSensor : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithPosition:(PigeonSensorPosition)position
    type:(PigeonSensorType)type
    deviceId:(nullable NSString *)deviceId;
@property(nonatomic, assign) PigeonSensorPosition position;
@property(nonatomic, assign) PigeonSensorType type;
@property(nonatomic, copy, nullable) NSString * deviceId;
@end

/// Video recording options. Some of them are specific to each platform.
@interface VideoOptions : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithEnableAudio:(NSNumber *)enableAudio
    quality:(VideoRecordingQuality)quality
    android:(nullable AndroidVideoOptions *)android
    ios:(nullable CupertinoVideoOptions *)ios;
/// Enable audio while video recording
@property(nonatomic, strong) NSNumber * enableAudio;
/// The quality of the video recording, defaults to [VideoRecordingQuality.highest].
@property(nonatomic, assign) VideoRecordingQuality quality;
@property(nonatomic, strong, nullable) AndroidVideoOptions * android;
@property(nonatomic, strong, nullable) CupertinoVideoOptions * ios;
@end

@interface AndroidVideoOptions : NSObject
+ (instancetype)makeWithBitrate:(nullable NSNumber *)bitrate
    fallbackStrategy:(QualityFallbackStrategy)fallbackStrategy;
/// The bitrate of the video recording. Only set it if a custom bitrate is
/// desired.
@property(nonatomic, strong, nullable) NSNumber * bitrate;
@property(nonatomic, assign) QualityFallbackStrategy fallbackStrategy;
@end

@interface CupertinoVideoOptions : NSObject
+ (instancetype)makeWithFileType:(CupertinoFileType)fileType
    codec:(CupertinoCodecType)codec
    fps:(nullable NSNumber *)fps;
/// Specify video file type, defaults to [AVFileTypeQuickTimeMovie].
@property(nonatomic, assign) CupertinoFileType fileType;
/// Specify video codec, defaults to [AVVideoCodecTypeH264].
@property(nonatomic, assign) CupertinoCodecType codec;
/// Specify video fps, defaults to [30].
@property(nonatomic, strong, nullable) NSNumber * fps;
@end

@interface PigeonSensorTypeDevice : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithSensorType:(PigeonSensorType)sensorType
    name:(NSString *)name
    iso:(NSNumber *)iso
    flashAvailable:(NSNumber *)flashAvailable
    uid:(NSString *)uid;
@property(nonatomic, assign) PigeonSensorType sensorType;
/// A localized device name for display in the user interface.
@property(nonatomic, copy) NSString * name;
/// The current exposure ISO value.
@property(nonatomic, strong) NSNumber * iso;
/// A Boolean value that indicates whether the flash is currently available for use.
@property(nonatomic, strong) NSNumber * flashAvailable;
/// An identifier that uniquely identifies the device.
@property(nonatomic, copy) NSString * uid;
@end

@interface AndroidFocusSettings : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithAutoCancelDurationInMillis:(NSNumber *)autoCancelDurationInMillis;
/// The auto focus will be canceled after the given [autoCancelDurationInMillis].
/// If [autoCancelDurationInMillis] is equals to 0 (or less), the auto focus
/// will **not** be canceled. A manual `focusOnPoint` call will be needed to
/// focus on an other point.
/// Minimal duration of [autoCancelDurationInMillis] is 1000 ms. If set
/// between 0 (exclusive) and 1000 (exclusive), it will be raised to 1000.
@property(nonatomic, strong) NSNumber * autoCancelDurationInMillis;
@end

@interface PlaneWrapper : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithBytes:(FlutterStandardTypedData *)bytes
    bytesPerRow:(NSNumber *)bytesPerRow
    bytesPerPixel:(nullable NSNumber *)bytesPerPixel
    width:(nullable NSNumber *)width
    height:(nullable NSNumber *)height;
@property(nonatomic, strong) FlutterStandardTypedData * bytes;
@property(nonatomic, strong) NSNumber * bytesPerRow;
@property(nonatomic, strong, nullable) NSNumber * bytesPerPixel;
@property(nonatomic, strong, nullable) NSNumber * width;
@property(nonatomic, strong, nullable) NSNumber * height;
@end

@interface CropRectWrapper : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithLeft:(NSNumber *)left
    top:(NSNumber *)top
    width:(NSNumber *)width
    height:(NSNumber *)height;
@property(nonatomic, strong) NSNumber * left;
@property(nonatomic, strong) NSNumber * top;
@property(nonatomic, strong) NSNumber * width;
@property(nonatomic, strong) NSNumber * height;
@end

@interface AnalysisImageWrapper : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithFormat:(AnalysisImageFormat)format
    bytes:(nullable FlutterStandardTypedData *)bytes
    width:(NSNumber *)width
    height:(NSNumber *)height
    planes:(nullable NSArray<PlaneWrapper *> *)planes
    cropRect:(nullable CropRectWrapper *)cropRect
    rotation:(AnalysisRotation)rotation;
@property(nonatomic, assign) AnalysisImageFormat format;
@property(nonatomic, strong, nullable) FlutterStandardTypedData * bytes;
@property(nonatomic, strong) NSNumber * width;
@property(nonatomic, strong) NSNumber * height;
@property(nonatomic, strong, nullable) NSArray<PlaneWrapper *> * planes;
@property(nonatomic, strong, nullable) CropRectWrapper * cropRect;
@property(nonatomic, assign) AnalysisRotation rotation;
@end

/// Snapshot of the device exposure capabilities and current values.
/// Durations are expressed in seconds.
///
/// iOS only for now.
@interface PigeonExposureState : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithMinIso:(NSNumber *)minIso
    maxIso:(NSNumber *)maxIso
    currentIso:(NSNumber *)currentIso
    minExposureDurationSeconds:(NSNumber *)minExposureDurationSeconds
    maxExposureDurationSeconds:(NSNumber *)maxExposureDurationSeconds
    currentExposureDurationSeconds:(NSNumber *)currentExposureDurationSeconds
    minExposureTargetBias:(NSNumber *)minExposureTargetBias
    maxExposureTargetBias:(NSNumber *)maxExposureTargetBias
    currentExposureTargetBias:(NSNumber *)currentExposureTargetBias;
@property(nonatomic, strong) NSNumber * minIso;
@property(nonatomic, strong) NSNumber * maxIso;
@property(nonatomic, strong) NSNumber * currentIso;
@property(nonatomic, strong) NSNumber * minExposureDurationSeconds;
@property(nonatomic, strong) NSNumber * maxExposureDurationSeconds;
@property(nonatomic, strong) NSNumber * currentExposureDurationSeconds;
@property(nonatomic, strong) NSNumber * minExposureTargetBias;
@property(nonatomic, strong) NSNumber * maxExposureTargetBias;
@property(nonatomic, strong) NSNumber * currentExposureTargetBias;
@end

/// RGB white balance gains mirroring
/// `AVCaptureDevice.WhiteBalanceGains`.
///
/// iOS only for now.
@interface PigeonWhiteBalanceGains : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithRed:(NSNumber *)red
    green:(NSNumber *)green
    blue:(NSNumber *)blue;
@property(nonatomic, strong) NSNumber * red;
@property(nonatomic, strong) NSNumber * green;
@property(nonatomic, strong) NSNumber * blue;
@end

/// A snapshot of the current device photo control values **and** their
/// supported ranges, read directly from `AVCaptureDevice`. Useful to
/// initialize a UI with the values that are actually applied.
///
/// iOS only for now.
@interface PigeonCameraSettings : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithExposureMode:(PigeonExposureMode)exposureMode
    exposureTargetBias:(NSNumber *)exposureTargetBias
    minExposureTargetBias:(NSNumber *)minExposureTargetBias
    maxExposureTargetBias:(NSNumber *)maxExposureTargetBias
    iso:(NSNumber *)iso
    minIso:(NSNumber *)minIso
    maxIso:(NSNumber *)maxIso
    exposureDurationSeconds:(NSNumber *)exposureDurationSeconds
    minExposureDurationSeconds:(NSNumber *)minExposureDurationSeconds
    maxExposureDurationSeconds:(NSNumber *)maxExposureDurationSeconds
    focusMode:(PigeonFocusMode)focusMode
    lensPosition:(NSNumber *)lensPosition
    whiteBalanceMode:(PigeonWhiteBalanceMode)whiteBalanceMode
    temperature:(NSNumber *)temperature
    tint:(NSNumber *)tint
    torchMode:(PigeonTorchMode)torchMode
    torchActive:(NSNumber *)torchActive
    lowLightBoostEnabled:(NSNumber *)lowLightBoostEnabled
    colorSpace:(PigeonColorSpace)colorSpace
    autoRedEyeReductionEnabled:(NSNumber *)autoRedEyeReductionEnabled
    zoomRatio:(NSNumber *)zoomRatio
    minZoomRatio:(NSNumber *)minZoomRatio
    maxZoomRatio:(NSNumber *)maxZoomRatio;
@property(nonatomic, assign) PigeonExposureMode exposureMode;
@property(nonatomic, strong) NSNumber * exposureTargetBias;
@property(nonatomic, strong) NSNumber * minExposureTargetBias;
@property(nonatomic, strong) NSNumber * maxExposureTargetBias;
@property(nonatomic, strong) NSNumber * iso;
@property(nonatomic, strong) NSNumber * minIso;
@property(nonatomic, strong) NSNumber * maxIso;
@property(nonatomic, strong) NSNumber * exposureDurationSeconds;
@property(nonatomic, strong) NSNumber * minExposureDurationSeconds;
@property(nonatomic, strong) NSNumber * maxExposureDurationSeconds;
@property(nonatomic, assign) PigeonFocusMode focusMode;
@property(nonatomic, strong) NSNumber * lensPosition;
@property(nonatomic, assign) PigeonWhiteBalanceMode whiteBalanceMode;
@property(nonatomic, strong) NSNumber * temperature;
@property(nonatomic, strong) NSNumber * tint;
@property(nonatomic, assign) PigeonTorchMode torchMode;
@property(nonatomic, strong) NSNumber * torchActive;
@property(nonatomic, strong) NSNumber * lowLightBoostEnabled;
@property(nonatomic, assign) PigeonColorSpace colorSpace;
@property(nonatomic, strong) NSNumber * autoRedEyeReductionEnabled;
@property(nonatomic, strong) NSNumber * zoomRatio;
@property(nonatomic, strong) NSNumber * minZoomRatio;
@property(nonatomic, strong) NSNumber * maxZoomRatio;
@end

/// The codec used by AnalysisImageUtils.
NSObject<FlutterMessageCodec> *AnalysisImageUtilsGetCodec(void);

@protocol AnalysisImageUtils
- (void)nv21toJpegNv21Image:(AnalysisImageWrapper *)nv21Image jpegQuality:(NSNumber *)jpegQuality completion:(void (^)(AnalysisImageWrapper *_Nullable, FlutterError *_Nullable))completion;
- (void)yuv420toJpegYuvImage:(AnalysisImageWrapper *)yuvImage jpegQuality:(NSNumber *)jpegQuality completion:(void (^)(AnalysisImageWrapper *_Nullable, FlutterError *_Nullable))completion;
- (void)yuv420toNv21YuvImage:(AnalysisImageWrapper *)yuvImage completion:(void (^)(AnalysisImageWrapper *_Nullable, FlutterError *_Nullable))completion;
- (void)bgra8888toJpegBgra8888image:(AnalysisImageWrapper *)bgra8888image jpegQuality:(NSNumber *)jpegQuality completion:(void (^)(AnalysisImageWrapper *_Nullable, FlutterError *_Nullable))completion;
@end

extern void AnalysisImageUtilsSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AnalysisImageUtils> *_Nullable api);

/// The codec used by CameraInterface.
NSObject<FlutterMessageCodec> *CameraInterfaceGetCodec(void);

@protocol CameraInterface
- (void)setupCameraSensors:(NSArray<PigeonSensor *> *)sensors aspectRatio:(NSString *)aspectRatio zoom:(NSNumber *)zoom mirrorFrontCamera:(NSNumber *)mirrorFrontCamera enablePhysicalButton:(NSNumber *)enablePhysicalButton flashMode:(NSString *)flashMode captureMode:(NSString *)captureMode enableImageStream:(NSNumber *)enableImageStream exifPreferences:(ExifPreferences *)exifPreferences videoOptions:(nullable VideoOptions *)videoOptions completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
/// @return `nil` only when `error != nil`.
- (nullable NSArray<NSString *> *)checkPermissionsPermissions:(NSArray<NSString *> *)permissions error:(FlutterError *_Nullable *_Nonnull)error;
/// Returns given [CamerAwesomePermission] list (as String). Location permission might be
/// refused but the app should still be able to run.
- (void)requestPermissionsSaveGpsLocation:(NSNumber *)saveGpsLocation completion:(void (^)(NSArray<NSString *> *_Nullable, FlutterError *_Nullable))completion;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)getPreviewTextureIdCameraPosition:(NSNumber *)cameraPosition error:(FlutterError *_Nullable *_Nonnull)error;
- (void)takePhotoSensors:(NSArray<PigeonSensor *> *)sensors paths:(NSArray<NSString *> *)paths completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)recordVideoSensors:(NSArray<PigeonSensor *> *)sensors paths:(NSArray<NSString *> *)paths completion:(void (^)(FlutterError *_Nullable))completion;
- (void)pauseVideoRecordingWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)resumeVideoRecordingWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)receivedImageFromStreamWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)stopRecordingVideoWithCompletion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
/// @return `nil` only when `error != nil`.
- (nullable NSArray<PigeonSensorTypeDevice *> *)getFrontSensorsWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSArray<PigeonSensorTypeDevice *> *)getBackSensorsWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)startWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)stopWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)setFlashModeMode:(NSString *)mode error:(FlutterError *_Nullable *_Nonnull)error;
- (void)handleAutoFocusWithError:(FlutterError *_Nullable *_Nonnull)error;
/// Starts auto focus on a point at ([x], [y]).
///
/// On Android, you can control after how much time you want to switch back
/// to passive focus mode with [androidFocusSettings].
- (void)focusOnPointPreviewSize:(PreviewSize *)previewSize x:(NSNumber *)x y:(NSNumber *)y androidFocusSettings:(nullable AndroidFocusSettings *)androidFocusSettings error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setZoomZoom:(NSNumber *)zoom error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setMirrorFrontCameraMirror:(NSNumber *)mirror error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setSensorSensors:(NSArray<PigeonSensor *> *)sensors error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setCorrectionBrightness:(NSNumber *)brightness error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)getMinZoomWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)getMaxZoomWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)setCaptureModeMode:(NSString *)mode error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setRecordingAudioModeEnableAudio:(NSNumber *)enableAudio completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
/// @return `nil` only when `error != nil`.
- (nullable NSArray<PreviewSize *> *)availableSizesWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)refreshWithError:(FlutterError *_Nullable *_Nonnull)error;
- (nullable PreviewSize *)getEffectivPreviewSizeIndex:(NSNumber *)index error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setPhotoSizeSize:(PreviewSize *)size error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setPreviewSizeSize:(PreviewSize *)size error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setAspectRatioAspectRatio:(NSString *)aspectRatio error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setupImageAnalysisStreamFormat:(NSString *)format width:(NSNumber *)width maxFramesPerSecond:(nullable NSNumber *)maxFramesPerSecond autoStart:(NSNumber *)autoStart error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setExifPreferencesExifPreferences:(ExifPreferences *)exifPreferences completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)startAnalysisWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)stopAnalysisWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)setFilterMatrix:(NSArray<NSNumber *> *)matrix error:(FlutterError *_Nullable *_Nonnull)error;
- (void)isVideoRecordingAndImageAnalysisSupportedSensor:(PigeonSensorPosition)sensor completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)isMultiCamSupportedWithError:(FlutterError *_Nullable *_Nonnull)error;
/// Set the [AVCaptureExposureMode]. See [PigeonExposureMode].
- (void)setExposureModeMode:(PigeonExposureMode)mode error:(FlutterError *_Nullable *_Nonnull)error;
/// Set the exposure point of interest at ([x], [y]) expressed in the
/// [previewSize] coordinate space.
- (void)setExposurePointX:(NSNumber *)x y:(NSNumber *)y previewSize:(PreviewSize *)previewSize error:(FlutterError *_Nullable *_Nonnull)error;
/// Set the absolute exposure target bias (EV), clamped to the device
/// supported range. Unlike [setCorrection] this takes a raw EV value.
- (void)setExposureTargetBiasBias:(NSNumber *)bias error:(FlutterError *_Nullable *_Nonnull)error;
/// Switch to custom exposure with the given [iso] and shutter speed
/// [exposureDurationSeconds] (in seconds), both clamped to the supported
/// range of the active format.
- (void)setManualExposureIso:(NSNumber *)iso exposureDurationSeconds:(NSNumber *)exposureDurationSeconds error:(FlutterError *_Nullable *_Nonnull)error;
/// Returns the current exposure capabilities and values of the device.
///
/// @return `nil` only when `error != nil`.
- (nullable PigeonExposureState *)getExposureStateWithError:(FlutterError *_Nullable *_Nonnull)error;
/// Returns a snapshot of all current photo control values and their
/// supported ranges, read directly from the active device. Useful to
/// initialize a UI with the values actually applied.
///
/// @return `nil` only when `error != nil`.
- (nullable PigeonCameraSettings *)getCameraSettingsWithError:(FlutterError *_Nullable *_Nonnull)error;
/// Set the [AVCaptureFocusMode]. See [PigeonFocusMode].
- (void)setFocusModeMode:(PigeonFocusMode)mode error:(FlutterError *_Nullable *_Nonnull)error;
/// Lock the focus at the given [lensPosition] (0.0 nearest, 1.0 farthest).
- (void)setLensPositionLensPosition:(NSNumber *)lensPosition error:(FlutterError *_Nullable *_Nonnull)error;
/// Returns the current lens position (0.0 to 1.0).
///
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)getLensPositionWithError:(FlutterError *_Nullable *_Nonnull)error;
/// Set the [AVCaptureDevice.AutoFocusRangeRestriction].
- (void)setAutoFocusRangeRestrictionRestriction:(PigeonFocusRangeRestriction)restriction error:(FlutterError *_Nullable *_Nonnull)error;
/// Enable or disable smooth autofocus.
- (void)setSmoothAutoFocusEnabledEnabled:(NSNumber *)enabled error:(FlutterError *_Nullable *_Nonnull)error;
/// Set the [AVCaptureWhiteBalanceMode]. See [PigeonWhiteBalanceMode].
- (void)setWhiteBalanceModeMode:(PigeonWhiteBalanceMode)mode error:(FlutterError *_Nullable *_Nonnull)error;
/// Lock the white balance using the given device RGB [gains].
- (void)setWhiteBalanceGainsGains:(PigeonWhiteBalanceGains *)gains error:(FlutterError *_Nullable *_Nonnull)error;
/// Lock the white balance using a [temperature] (Kelvin) and [tint].
- (void)setWhiteBalanceTemperatureTintTemperature:(NSNumber *)temperature tint:(NSNumber *)tint error:(FlutterError *_Nullable *_Nonnull)error;
/// Returns the current device white balance gains.
///
/// @return `nil` only when `error != nil`.
- (nullable PigeonWhiteBalanceGains *)getWhiteBalanceGainsWithError:(FlutterError *_Nullable *_Nonnull)error;
/// Returns the maximum supported white balance gain for the active device.
///
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)getMaxWhiteBalanceGainWithError:(FlutterError *_Nullable *_Nonnull)error;
/// Lock the white balance using the gray world estimate of the current scene.
- (void)setGrayWorldWhiteBalanceWithError:(FlutterError *_Nullable *_Nonnull)error;
/// Set the [AVCaptureTorchMode]. See [PigeonTorchMode]. Independent of the
/// photo flash configured through [setFlashMode].
- (void)setTorchModeMode:(PigeonTorchMode)mode error:(FlutterError *_Nullable *_Nonnull)error;
/// Turn on the torch at the given [level] (0.0 to 1.0).
- (void)setTorchLevelLevel:(NSNumber *)level error:(FlutterError *_Nullable *_Nonnull)error;
/// Returns whether the torch is currently active.
///
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)isTorchActiveWithError:(FlutterError *_Nullable *_Nonnull)error;
/// Enable or disable automatic low light boost when available.
- (void)setLowLightBoostEnabledEnabled:(NSNumber *)enabled error:(FlutterError *_Nullable *_Nonnull)error;
/// Returns whether low light boost is supported by the active device.
///
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)isLowLightBoostSupportedWithError:(FlutterError *_Nullable *_Nonnull)error;
/// Set the active [AVCaptureColorSpace]. See [PigeonColorSpace].
- (void)setColorSpaceColorSpace:(PigeonColorSpace)colorSpace error:(FlutterError *_Nullable *_Nonnull)error;
/// Returns the color spaces supported by the active format (as names of
/// [PigeonColorSpace]).
///
/// @return `nil` only when `error != nil`.
- (nullable NSArray<NSString *> *)getAvailableColorSpacesWithError:(FlutterError *_Nullable *_Nonnull)error;
/// Enable or disable automatic red eye reduction on the photo output.
- (void)setAutoRedEyeReductionEnabledEnabled:(NSNumber *)enabled error:(FlutterError *_Nullable *_Nonnull)error;
/// Set the absolute zoom factor (videoZoomFactor), clamped to the supported
/// range.
- (void)setZoomRatioRatio:(NSNumber *)ratio error:(FlutterError *_Nullable *_Nonnull)error;
/// Returns the minimum available zoom factor.
///
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)getMinZoomRatioWithError:(FlutterError *_Nullable *_Nonnull)error;
/// Returns the maximum available zoom factor.
///
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)getMaxZoomRatioWithError:(FlutterError *_Nullable *_Nonnull)error;
/// Smoothly ramp the zoom to [ratio] at the given [rate].
- (void)rampToZoomRatioRatio:(NSNumber *)ratio rate:(NSNumber *)rate error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void CameraInterfaceSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<CameraInterface> *_Nullable api);

NS_ASSUME_NONNULL_END
